# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bee_pb2 as bee__pb2


class BeeServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartBee = channel.unary_unary(
                '/BeeServer/StartBee',
                request_serializer=bee__pb2.StartRequest.SerializeToString,
                response_deserializer=bee__pb2.StartReply.FromString,
                )
        self.SubmitWord = channel.unary_unary(
                '/BeeServer/SubmitWord',
                request_serializer=bee__pb2.SubmitWordRequest.SerializeToString,
                response_deserializer=bee__pb2.SubmitWordReply.FromString,
                )
        self.CreateBee = channel.unary_unary(
                '/BeeServer/CreateBee',
                request_serializer=bee__pb2.CreateRequest.SerializeToString,
                response_deserializer=bee__pb2.CreateReply.FromString,
                )
        self.JoinBee = channel.unary_unary(
                '/BeeServer/JoinBee',
                request_serializer=bee__pb2.JoinRequest.SerializeToString,
                response_deserializer=bee__pb2.JoinReply.FromString,
                )


class BeeServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartBee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinBee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeeServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartBee': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBee,
                    request_deserializer=bee__pb2.StartRequest.FromString,
                    response_serializer=bee__pb2.StartReply.SerializeToString,
            ),
            'SubmitWord': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitWord,
                    request_deserializer=bee__pb2.SubmitWordRequest.FromString,
                    response_serializer=bee__pb2.SubmitWordReply.SerializeToString,
            ),
            'CreateBee': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBee,
                    request_deserializer=bee__pb2.CreateRequest.FromString,
                    response_serializer=bee__pb2.CreateReply.SerializeToString,
            ),
            'JoinBee': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinBee,
                    request_deserializer=bee__pb2.JoinRequest.FromString,
                    response_serializer=bee__pb2.JoinReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BeeServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BeeServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartBee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BeeServer/StartBee',
            bee__pb2.StartRequest.SerializeToString,
            bee__pb2.StartReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BeeServer/SubmitWord',
            bee__pb2.SubmitWordRequest.SerializeToString,
            bee__pb2.SubmitWordReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BeeServer/CreateBee',
            bee__pb2.CreateRequest.SerializeToString,
            bee__pb2.CreateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinBee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BeeServer/JoinBee',
            bee__pb2.JoinRequest.SerializeToString,
            bee__pb2.JoinReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
