# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bee.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bee.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tbee.proto\"\x0e\n\x0cStartRequest\"\x1d\n\nStartReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"5\n\x11SubmitWordRequest\x12\x0e\n\x06wordIn\x18\x01 \x01(\t\x12\x10\n\x08playerID\x18\x02 \x01(\x05\"!\n\x0fSubmitWordReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\" \n\rCreateRequest\x12\x0f\n\x07\x62\x65\x65Type\x18\x01 \x01(\x05\"\x1e\n\x0b\x43reateReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0bJoinRequest\x12\x0e\n\x06gameID\x18\x01 \x01(\t\"2\n\tJoinReply\x12\x13\n\x0bjoinMessage\x18\x01 \x01(\t\x12\x10\n\x08playerID\x18\x02 \x01(\x05\x32\xbf\x01\n\tBeeServer\x12(\n\x08StartBee\x12\r.StartRequest\x1a\x0b.StartReply\"\x00\x12\x34\n\nSubmitWord\x12\x12.SubmitWordRequest\x1a\x10.SubmitWordReply\"\x00\x12+\n\tCreateBee\x12\x0e.CreateRequest\x1a\x0c.CreateReply\"\x00\x12%\n\x07JoinBee\x12\x0c.JoinRequest\x1a\n.JoinReply\"\x00\x62\x06proto3'
)




_STARTREQUEST = _descriptor.Descriptor(
  name='StartRequest',
  full_name='StartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=27,
)


_STARTREPLY = _descriptor.Descriptor(
  name='StartReply',
  full_name='StartReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='StartReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=58,
)


_SUBMITWORDREQUEST = _descriptor.Descriptor(
  name='SubmitWordRequest',
  full_name='SubmitWordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordIn', full_name='SubmitWordRequest.wordIn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playerID', full_name='SubmitWordRequest.playerID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=113,
)


_SUBMITWORDREPLY = _descriptor.Descriptor(
  name='SubmitWordReply',
  full_name='SubmitWordReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SubmitWordReply.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=148,
)


_CREATEREQUEST = _descriptor.Descriptor(
  name='CreateRequest',
  full_name='CreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='beeType', full_name='CreateRequest.beeType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=182,
)


_CREATEREPLY = _descriptor.Descriptor(
  name='CreateReply',
  full_name='CreateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='CreateReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=214,
)


_JOINREQUEST = _descriptor.Descriptor(
  name='JoinRequest',
  full_name='JoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameID', full_name='JoinRequest.gameID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=245,
)


_JOINREPLY = _descriptor.Descriptor(
  name='JoinReply',
  full_name='JoinReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='joinMessage', full_name='JoinReply.joinMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playerID', full_name='JoinReply.playerID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=297,
)

DESCRIPTOR.message_types_by_name['StartRequest'] = _STARTREQUEST
DESCRIPTOR.message_types_by_name['StartReply'] = _STARTREPLY
DESCRIPTOR.message_types_by_name['SubmitWordRequest'] = _SUBMITWORDREQUEST
DESCRIPTOR.message_types_by_name['SubmitWordReply'] = _SUBMITWORDREPLY
DESCRIPTOR.message_types_by_name['CreateRequest'] = _CREATEREQUEST
DESCRIPTOR.message_types_by_name['CreateReply'] = _CREATEREPLY
DESCRIPTOR.message_types_by_name['JoinRequest'] = _JOINREQUEST
DESCRIPTOR.message_types_by_name['JoinReply'] = _JOINREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREQUEST,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:StartRequest)
  })
_sym_db.RegisterMessage(StartRequest)

StartReply = _reflection.GeneratedProtocolMessageType('StartReply', (_message.Message,), {
  'DESCRIPTOR' : _STARTREPLY,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:StartReply)
  })
_sym_db.RegisterMessage(StartReply)

SubmitWordRequest = _reflection.GeneratedProtocolMessageType('SubmitWordRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITWORDREQUEST,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:SubmitWordRequest)
  })
_sym_db.RegisterMessage(SubmitWordRequest)

SubmitWordReply = _reflection.GeneratedProtocolMessageType('SubmitWordReply', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITWORDREPLY,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:SubmitWordReply)
  })
_sym_db.RegisterMessage(SubmitWordReply)

CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREQUEST,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:CreateRequest)
  })
_sym_db.RegisterMessage(CreateRequest)

CreateReply = _reflection.GeneratedProtocolMessageType('CreateReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREPLY,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:CreateReply)
  })
_sym_db.RegisterMessage(CreateReply)

JoinRequest = _reflection.GeneratedProtocolMessageType('JoinRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINREQUEST,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:JoinRequest)
  })
_sym_db.RegisterMessage(JoinRequest)

JoinReply = _reflection.GeneratedProtocolMessageType('JoinReply', (_message.Message,), {
  'DESCRIPTOR' : _JOINREPLY,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:JoinReply)
  })
_sym_db.RegisterMessage(JoinReply)



_BEESERVER = _descriptor.ServiceDescriptor(
  name='BeeServer',
  full_name='BeeServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=300,
  serialized_end=491,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartBee',
    full_name='BeeServer.StartBee',
    index=0,
    containing_service=None,
    input_type=_STARTREQUEST,
    output_type=_STARTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitWord',
    full_name='BeeServer.SubmitWord',
    index=1,
    containing_service=None,
    input_type=_SUBMITWORDREQUEST,
    output_type=_SUBMITWORDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateBee',
    full_name='BeeServer.CreateBee',
    index=2,
    containing_service=None,
    input_type=_CREATEREQUEST,
    output_type=_CREATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='JoinBee',
    full_name='BeeServer.JoinBee',
    index=3,
    containing_service=None,
    input_type=_JOINREQUEST,
    output_type=_JOINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BEESERVER)

DESCRIPTOR.services_by_name['BeeServer'] = _BEESERVER

# @@protoc_insertion_point(module_scope)
