# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bee.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bee.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tbee.proto\"\x0e\n\x0cStartRequest\"\x1d\n\nStartReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x11SubmitWordRequest\x12\x0e\n\x06wordIn\x18\x01 \x01(\t\"!\n\x0fSubmitWordReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32k\n\tBeeServer\x12(\n\x08StartBee\x12\r.StartRequest\x1a\x0b.StartReply\"\x00\x12\x34\n\nSubmitWord\x12\x12.SubmitWordRequest\x1a\x10.SubmitWordReply\"\x00\x62\x06proto3'
)




_STARTREQUEST = _descriptor.Descriptor(
  name='StartRequest',
  full_name='StartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=27,
)


_STARTREPLY = _descriptor.Descriptor(
  name='StartReply',
  full_name='StartReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='StartReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=58,
)


_SUBMITWORDREQUEST = _descriptor.Descriptor(
  name='SubmitWordRequest',
  full_name='SubmitWordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordIn', full_name='SubmitWordRequest.wordIn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=95,
)


_SUBMITWORDREPLY = _descriptor.Descriptor(
  name='SubmitWordReply',
  full_name='SubmitWordReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SubmitWordReply.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['StartRequest'] = _STARTREQUEST
DESCRIPTOR.message_types_by_name['StartReply'] = _STARTREPLY
DESCRIPTOR.message_types_by_name['SubmitWordRequest'] = _SUBMITWORDREQUEST
DESCRIPTOR.message_types_by_name['SubmitWordReply'] = _SUBMITWORDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREQUEST,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:StartRequest)
  })
_sym_db.RegisterMessage(StartRequest)

StartReply = _reflection.GeneratedProtocolMessageType('StartReply', (_message.Message,), {
  'DESCRIPTOR' : _STARTREPLY,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:StartReply)
  })
_sym_db.RegisterMessage(StartReply)

SubmitWordRequest = _reflection.GeneratedProtocolMessageType('SubmitWordRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITWORDREQUEST,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:SubmitWordRequest)
  })
_sym_db.RegisterMessage(SubmitWordRequest)

SubmitWordReply = _reflection.GeneratedProtocolMessageType('SubmitWordReply', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITWORDREPLY,
  '__module__' : 'bee_pb2'
  # @@protoc_insertion_point(class_scope:SubmitWordReply)
  })
_sym_db.RegisterMessage(SubmitWordReply)



_BEESERVER = _descriptor.ServiceDescriptor(
  name='BeeServer',
  full_name='BeeServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=132,
  serialized_end=239,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartBee',
    full_name='BeeServer.StartBee',
    index=0,
    containing_service=None,
    input_type=_STARTREQUEST,
    output_type=_STARTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitWord',
    full_name='BeeServer.SubmitWord',
    index=1,
    containing_service=None,
    input_type=_SUBMITWORDREQUEST,
    output_type=_SUBMITWORDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BEESERVER)

DESCRIPTOR.services_by_name['BeeServer'] = _BEESERVER

# @@protoc_insertion_point(module_scope)
